name: Java CI + Run WAR

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest   # ✅ change from windows

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build WAR
      run: mvn clean package -DskipTests

    - name: Download Tomcat
      run: |
        wget https://downloads.apache.org/tomcat/tomcat-10/v10.1.20/bin/apache-tomcat-10.1.20.tar.gz
        tar -xzf apache-tomcat-10.1.20.tar.gz

    - name: Deploy WAR to Tomcat
      run: |
        cp target/*.war apache-tomcat-10.1.20/webapps/ROOT.war

    - name: Start Tomcat
      run: |
        chmod +x apache-tomcat-10.1.20/bin/*.sh
        apache-tomcat-10.1.20/bin/startup.sh

    - name: Wait and Test
      run: |
        sleep 20
        curl http://localhost:8080
