name: Build and Run App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build
      run: mvn clean package -DskipTests

    - name: Run Tests
      run: mvn test

    - name: Run App
      run: |
        nohup java -jar target/*.jar > app.log 2>&1 &

    - name: Wait to verify app
      run: sleep 20
